name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: setup.py

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8

      - name: Install molplotly + dependencies
        run: |
          pip install .[test]
          pip install rdkit-pypi

      - name: Run tests
        run: pytest --cov molplotly
